-- AlterTable
ALTER TABLE `synologyaccount` ADD COLUMN `app_priv_active_backup` VARCHAR(50) NULL,
    ADD COLUMN `app_priv_afp` VARCHAR(50) NULL,
    ADD COLUMN `app_priv_cloud_sync` VARCHAR(50) NULL,
    ADD COLUMN `app_priv_cms` VARCHAR(50) NULL,
    ADD COLUMN `app_priv_drive` VARCHAR(50) NULL,
    ADD COLUMN `app_priv_dsm` VARCHAR(50) NULL,
    ADD COLUMN `app_priv_file_station` VARCHAR(50) NULL,
    ADD COLUMN `app_priv_ftp` VARCHAR(50) NULL,
    ADD COLUMN `app_priv_mail_server` VARCHAR(50) NULL,
    ADD COLUMN `app_priv_notification` VARCHAR(50) NULL,
    ADD COLUMN `app_priv_rsync` VARCHAR(50) NULL,
    ADD COLUMN `app_priv_sftp` VARCHAR(50) NULL,
    ADD COLUMN `app_priv_smb` VARCHAR(50) NULL,
    ADD COLUMN `app_priv_universal_search` VARCHAR(50) NULL,
    ADD COLUMN `app_priv_vmm` VARCHAR(50) NULL,
    ADD COLUMN `description` TEXT NULL,
    ADD COLUMN `name_synology` VARCHAR(100) NULL,
    ADD COLUMN `quota_mb` VARCHAR(50) NULL,
    ADD COLUMN `two_fa_status` VARCHAR(50) NULL,
    ADD COLUMN `user_groups` TEXT NULL;
